### ISSUE TITLE
TODO: features to implement before 0.2.1

### ISSUE THREAD

**Issue by Trinsdar** [GT-Reimagined/GT5-Reimagined#1]
features for 0.2:

- [x] oil driling rig
- [x] oil wells
- [x] tree harvester
- [x] crop harvester
- [x] pump
- [x] long distance pipes
- [x] quadruple and nonuple fluid pipes
- [x] fluid pipe change to gt6 sloshing system
- [x] slight gui refacotor
- [x] air vent
- [x] scanner
- [x] replicator
- [x] amp fabricator
- [x] mass fabricator
- [x] machine control cover
- [x] shutter cover
- [x] fluid filter cover
- [x] make item filter a cover
- [x] multiblock tanks
- [x] large turbine
- [x] large diesel gen
- [x] cryo distillation tower
- [x] change tools to not be nbt based for the most part.

recipes for 0.2
- [x] arc furnace/macerator recycling
- [x] field gens
- [x] fluid regulators
- [x] air distillation

after 0.2

- [x] fusion
- [x] fission
- [x] miner multiblock
- [x] bedrock miner
- [x] miniature nether portal
- [x] air valve
- [x] fluid regulator cover
- [x] redstone transmitter
- [x] redstone receiver
- [x] progress sensor
- [x] item retriever

**Comment by Trinsdar** [comment]
0.2.1:

 - [x] Stone block based covers
-  [x] Override vanilla basalt texture using dynamic resource pack
 - [x] Somehow turn red alloy cables into something like red power red alloy wire for transferring redstone, soldering alloy will become the new ulv cable
-  [x] Gt6 like wrench pickup
 - [x] disable twilight uncrafting table recipes for everything gt
 - [x] needs maintenance cover
 - [x] info to give when using a scanner vs a magnifying glass
 - [x] lv assembly line for autocrafting crafting table recipes
 - [x] large ore washer
 - [x] large bath
 - [x] large autoclave
 - [x] crystallization chamber and boules
